### ISSUE TITLE
Failure to pull postgres image on `astro airflow start`

### ISSUE THREAD

**Issue by stant099** [astronomer/astro-cli#174] opened 2019-01-30 16:29 UTC
Hello - I am new to using the `astro-cli` and thought I'd report an issue I experienced during initial use.  This could be an issue on my end:

*  `postgres:10.1-alpine` image does not pull successfully on initial run of `astro airflow start`
*  This occurs when `postgres:10.1-alpine` image does not exist locally
*  This issue is resolved after manually pulling the `postgres:10.1-alpine` image
*  OS: Ubuntu 18.04.1 LTS
*  Docker version: 18.09.1, build 4c52b90

```
$ astro airflow start
Sending build context to Docker daemon  9.728kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.9.0-onbuild
0.7.5-1.9.0-onbuild: Pulling from astronomerinc/ap-airflow
4fe2ade4980c: Pull complete 
053771da3f31: Pull complete 
5590a17cde1a: Pull complete 
1e4120a9e66b: Pull complete 
cd829da03107: Pull complete 
e4d1e450568e: Pull complete 
dfca5184d175: Pull complete 
Digest: sha256:9a9db6e62f7d12a1e347cc3bebbbb832cb0c81973a5f842533741bf2040657d8
Status: Downloaded newer image for astronomerinc/ap-airflow:0.7.5-1.9.0-onbuild
# Executing 5 build triggers
 ---> Running in 53de9af37056
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
OK: 89 MiB in 37 packages
Removing intermediate container 53de9af37056
 ---> Running in 0f08e2cf2720
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 0f08e2cf2720
 ---> 3ec28d4320a5
Successfully built 3ec28d4320a5
Successfully tagged hello-astro/airflow:latest
INFO[0037] [0/3] [postgres]: Starting                   
Pulling postgres (postgres:10.1-alpine)...
panic: runtime error: index out of range

goroutine 27 [running]:
github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty.readTermInfo(0xc4202b1aa0, 0x1e, 0x0, 0x0, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty/gotty.go:232 +0xcc4
github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty.OpenTermInfo(0xc4200221c5, 0xe, 0xc4200221c5, 0xe, 0xc8)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty/gotty.go:45 +0x261
github.com/astronomer/astro-cli/vendor/github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0xb1e3e0, 0xc4205265c0, 0xb1e5c0, 0xc4200c4010, 0x2, 0x1, 0x0, 0x4, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:245 +0x53c
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/image.PullImage(0xb24140, 0xc4200c0030, 0x7fc57de7a380, 0xc42042c100, 0xc4200c0138, 0x8, 0xb20c00, 0xc42041e058, 0xc4200c2c40, 0x14, ...)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/image/image.go:83 +0x51b
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service.(*Service).Pull(0xc4203f0140, 0xb24140, 0xc4200c0030, 0xc42042c100, 0xc4200c2c40)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service/service.go:629 +0x119
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service.(*Service).ensureImageExists(0xc4203f0140, 0xb24140, 0xc4200c0030, 0x1060000, 0x0, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service/service.go:157 +0x251
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service.(*Service).Up(0xc4203f0140, 0xb24140, 0xc4200c0030, 0xc400000000, 0x8, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service/service.go:237 +0xcb
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*Project).Up.func1.1(0xb2b7c0, 0xc4203f0140, 0xc4200c0138, 0x8)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/project_up.go:17 +0x69
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*serviceWrapper).Do(0xc4201dca80, 0xc42044b440, 0x4, 0x6, 0xc420309fa0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/service-wrapper.go:101 +0x12c
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*Project).Up.func1(0xc4201dca80, 0xc42044b440)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/project_up.go:16 +0x9e
created by github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*Project).startService
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/project.go:448 +0x93e
```
* Manually pulled `postgres:10.1-alpine`
```
$ docker pull postgres:10.1-alpine
10.1-alpine: Pulling from library/postgres
605ce1bd3f31: Pull complete 
8d2abe692710: Pull complete 
a18eca080102: Pull complete 
91cfdfa52a99: Pull complete 
452cbf05af6d: Pull complete 
4a256b03e5bd: Pull complete 
379c8298095d: Pull complete 
12207b3814c9: Pull complete 
373a2b3fdfa1: Pull complete 
Digest: sha256:d6150452877361e26d0fd178d278af8f80d59c75cbb5c2413cfb4fdb5ed4f750
Status: Downloaded newer image for postgres:10.1-alpine
```
* Containers spin up successfully after manually pulling `postgres:10.1-alpine`
```
$ astro airflow start
Sending build context to Docker daemon  11.26kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.9.0-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> b27f461ad9d8
Successfully built b27f461ad9d8
Successfully tagged hello-astro/airflow:latest
INFO[0000] [0/3] [postgres]: Starting                   
INFO[0000] [1/3] [postgres]: Started                    
INFO[0000] [1/3] [scheduler]: Starting                  
INFO[0001] [2/3] [scheduler]: Started                   
INFO[0001] [2/3] [webserver]: Starting                  
INFO[0002] [3/3] [webserver]: Started                   
Airflow Webserver: http://localhost:8080/admin/
Postgres Database: localhost:5432/postgres
```

* I recreated this issue by removing the `postgres:10.1-alpine` container and image:
```
$ docker container rm <CONTAINER_ID>
...
$ docker image rm postgres:10.1-alpine
...
$ astro airflow start
Sending build context to Docker daemon  11.26kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.9.0-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> b27f461ad9d8
Successfully built b27f461ad9d8
Successfully tagged hello-astro/airflow:latest
INFO[0000] [0/3] [postgres]: Starting                   
Pulling postgres (postgres:10.1-alpine)...
panic: runtime error: index out of range
...
```

-Ian

**Comment by schnie** [comment] 2019-01-30 18:12
Interesting. Typically the images should be pulled automatically if they don't exist. @stant099 did the `astronomerinc/ap-airflow` image already exist on your machine before this?

@benjamingregory have you seen this at all?

**Comment by benjamingregory** [comment] 2019-01-30 18:12
Thanks for this issue @stant099. I just tried removing the `postgres:10.1-alpine` image and starting a new project and it pulled the remote image as intended.

```
MacBook-Pro-7:postgres tardis5$ astro airflow start
Sending build context to Docker daemon  20.48kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.9.0-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> 881219ff1888
Successfully built 881219ff1888
Successfully tagged postgres/airflow:latest
Creating network "postgres_airflow" with driver "bridge"
Creating volume "postgres_airflow_logs" with driver "local"
Creating volume "postgres_postgres_data" with driver "local"
INFO[0016] [0/3] [postgres]: Starting                   
Pulling postgres (postgres:10.1-alpine)...
10.1-alpine: Pulling from library/postgres
605ce1bd3f31: Pull complete 
8d2abe692710: Pull complete 
a18eca080102: Pull complete 
91cfdfa52a99: Pull complete 
452cbf05af6d: Pull complete 
4a256b03e5bd: Pull complete 
379c8298095d: Pull complete 
12207b3814c9: Pull complete 
373a2b3fdfa1: Pull complete 
Digest: sha256:d6150452877361e26d0fd178d278af8f80d59c75cbb5c2413cfb4fdb5ed4f750
Status: Downloaded newer image for postgres:10.1-alpine
INFO[0025] [1/3] [postgres]: Started                    
INFO[0025] [1/3] [scheduler]: Starting                  
INFO[0026] [2/3] [scheduler]: Started                   
INFO[0026] [2/3] [webserver]: Starting                  
INFO[0027] [3/3] [webserver]: Started                   
Airflow Webserver: http://localhost:8080/admin/
Postgres Database: localhost:5432/postgres
```

**Comment by benjamingregory** [comment] 2019-01-30 18:14
@stant099 -- What is the output of `astro version`?

**Comment by benjamingregory** [comment] 2019-02-08 18:26
Closing with our recommended fix:

https://forum.astronomer.io/t/i-get-a-pulling-postgres-postgres-10-1-alpine-panic-runtime-error-index-out-of-range-when-i-try-to-astro-airflow-start/133

**Closed by benjamingregory** 2019-02-08 18:26 UTC
Labels: area/cli, kind/bug
