### ISSUE TITLE
`astro deploy` on v1.19.0 fails when checking DAG parsing

### ISSUE THREAD

**Issue by tkmcc** [astronomer/astro-cli#1374] opened 2023-08-29 21:20 UTC
**Describe the bug**

When running `astro deploy our_deployment_id` from our CICD, the command ends with a failure.

Updating our script to pin to the latest working version mitigates the issue:
```
curl -sSL install.astronomer.io | sudo bash -s -- v1.18.2
```

Here is the failure log:

```
Checking your DAGs for errors,
this might take a minute if you haven't run this command before…
ERROR: file or directory not found: .astro/test_dag_integrity_default.py

============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /usr/local/airflow
configfile: pytest.ini
plugins: anyio-3.6.2
collected 0 items

============================ no tests ran in 0.01s =============================
Error: your local DAGs did not parse. Fix the listed errors or use `astro deploy [deployment-id] -f` to force deploy
something went wrong while parsing your DAGs: failed to execute cmd: exit status 4
Error: Process completed with exit code 1.
```

**What CLI Version did you experience this bug?**

1.19.0

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

Run `astro deploy your_deployment_id`

**Comment by neel-astro** [comment] 2023-08-30 08:18
could you validate whether the `.astro` folder exists in your image or not at `/usr/local/airflow` with the 1.19.0 CLI version? Also, what is the docker version in your setup?

**Comment by tangi-vass** [comment] 2023-08-30 10:20
I have the same issue with v1.19.0 since its release this night.

My setting:
```
FROM quay.io/astronomer/astro-runtime:9.0.0-python-3.10
```

I do have a .astro directory in my repo and it used to work yesterday evening.

Today, `astro dev parse --env ./config/variables/dev` causes this error:
```
 => CACHED [6/1] COPY --chown=astro:0 . .                                                                                                                                                                                                                                                                          0.0s
 => exporting to image                                                                                                                                                                                                                                                                                             0.0s
 => => exporting layers                                                                                                                                                                                                                                                                                            0.0s
 => => writing image sha256:751c461668afe5b35d85702057d27f31ded3efb2e252932c38e634f3e1e92112                                                                                                                                                                                                                       0.0s
 => => naming to docker.io/astronomer-refineries_945709/airflow:latest                                                                                                                                                                                                                                             0.0s
8a68edaa600b6788d67ccf49d279d3e0bc60c7c86217bab72fc4d42589c93859
                                             Successfully copied 136kB to astro-pytest:/usr/local/airflow/
ERROR: file or directory not found: .astro/test_dag_integrity_default.py
```

Could this issue be caused by https://github.com/astronomer/astro-cli/pull/1351/files#diff-5007101786b5bb38ed7776d83fe96c1f8e3f61f6eec586c7edd20fce2c2b9e7eL111 ?

**Comment by neel-astro** [comment] 2023-08-30 10:35
> I do have a .astro directory in my repo and it used to work yesterday evening.

@tangi-vass Is it present as part of the `docker.io/astronomer-refineries_945709/airflow:latest ` image?

> Could this issue be caused by https://github.com/astronomer/astro-cli/pull/1351/files#diff-5007101786b5bb38ed7776d83fe96c1f8e3f61f6eec586c7edd20fce2c2b9e7eL111 ?

Could be, trying to figure out if `.astro` is missing in the image that is being built for you guys, since the tests I ran as part of that change indicated that the docker image comes with `.astro` (Reference: https://user-images.githubusercontent.com/92356010/259775013-59c2a990-3f87-441e-827f-f9588b583b24.png) folder, hence I had removed the volume mount and didn't replace it with anything else.

**Comment by tangi-vass** [comment] 2023-08-30 10:42
Is it present as part of the docker.io/astronomer-refineries_945709/airflow:latest image?

I'm currently AFK so I can't check this specific image but nothing has changed on this regards recently, especially nothing at all this night for sure.

**Comment by davidlsq** [comment] 2023-08-30 11:07
Hello, I also had the `ERROR: file or directory not found: .astro/test_dag_integrity_default.py` issue this morning
The cause was `.astro` in `.dockerignore`, I fix it by adding `!.astro/test_dag_integrity_default.py`

**Comment by tangi-vass** [comment] 2023-08-30 11:53
David's solution worked for me :pray:

**Comment by neel-astro** [comment] 2023-08-30 17:42
Have added a fix as part of `1.19.1` CLI release, could you guys try that out and let me know if that fixes this issue?
cc @tkmcc @tangi-vass @davidlsq

**Comment by tangi-vass** [comment] 2023-08-31 06:52
@neel-astro Your fix works fine. Thank you.

**Comment by neel-astro** [comment] 2023-08-31 11:50
@tangi-vass thanks for the confirmation, I will close this issue then. Please feel free to reopen if you have any other concerns or issues.

**Closed by neel-astro** 2023-08-31 11:50 UTC
