### ISSUE TITLE
Shift the CI/CD Enforcement Check Left

### ISSUE THREAD

**Issue by ReadytoRocc** [astronomer/astro-cli#1282] opened 2023-06-23 18:36 UTC
Currently, `astro deploy` will pull, build, test, and push my image to Astro, before checking if CI/CD enforcement has been enabled on the target Runtime deployment.

Is it possible to initially check if CI/CD enforcement has been enabled to fail fast and inform the user that this action is not allowed? 

This will save users' time and resources.

**Comment by kushalmalani** [comment] 2023-06-26 07:11
Duplicate of (https://github.com/astronomer/astro-cli/issues/1276)

**Closed** 2023-08-01 16:13 UTC
Labels: app/astro-cli, team/hosted-dataplane
