### ISSUE TITLE
astro deployment update name removes all dags

### ISSUE THREAD

**Issue by adammarples** [astronomer/astro-cli#1458] opened 2023-11-22 13:48 UTC
**Describe the bug**

```bash
astro deployment update --deployment-name SRC_NAME --name DST_NAME
```

Will rename the deployment but lose all its dags, the only one left is astronomer_monitoring_dag

**What CLI Version did you experience this bug?**

1.20.1

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

MacOS Sonoma 14.1.1

**🪜 Steps To Reproduce**

1. Create a deployment
2. Deploy some dags
3. Run 
```bash
astro deployment update --deployment-name SRC_NAME --name DST_NAME
```
4. wait for HEALTHY status
5. look at the dags

**📸 Screenshots**

![image](https://github.com/astronomer/astro-cli/assets/22686431/d034df1f-cc95-49b5-95c8-eaa4803a9301)

![image](https://github.com/astronomer/astro-cli/assets/22686431/89f8e750-91c7-478b-a8a0-433f98d7fd94)

**Comment by kushalmalani** [comment] 2023-11-28 04:13
@adammarples I am unable to reproduce this. I tried following your steps and i see my dags are running fine

<img width="599" alt="Screenshot 2023-11-27 at 20 12 47" src="https://github.com/astronomer/astro-cli/assets/65428224/9112ed84-56a7-4476-88cd-b8a404ba8d55">
<img width="1707" alt="Screenshot 2023-11-27 at 20 12 58" src="https://github.com/astronomer/astro-cli/assets/65428224/cc5e73c9-2d65-49b0-b736-04a3bfb63cc0">

Could you reproduce and share the deployment information via Zendesk ticket so we can debug?

**Comment by kushalmalani** [comment] 2023-11-28 22:33
@adammarples I think we observed this issue internally. We are going to debug and patch this. Will keep you updated once the fix is out.

**Comment by adammarples** [comment] 2023-11-29 10:44
Thank @kushalmalani, please do. Will this require upgrading to a new version of the tool?

**Comment by kushalmalani** [comment] 2023-11-29 20:01
Yes, since this is a CLI bug. I see similar issue in prior versions also. We are also extending our test cases to validate that this field shouldnt change on update unless explicitly done by the user. I will drop a note once a release is out.

**Comment by adammarples** [comment] 2023-11-30 09:12
@kushalmalani because you were able to show a working example which did not delete the dags, is there some workaround I can implement in the meantime that you were able to do that I was not? Thanks

**Comment by sunkickr** [comment] 2023-11-30 17:26
@adammarples unfortunately the `astro deployment update` is broken for deployment with dag-deploy enabled only work around would be disabling dag-deploy. Their should be a new CLI release by monday

**Comment by kushalmalani** [comment] 2023-12-04 21:35
@adammarples This should be fixed in cli release 1.21.0, which should not be available to install. Can you upgrade and try that version?

**Comment by adammarples** [comment] 2023-12-05 10:35
@kushalmalani that works, thank you

**Comment by adammarples** [comment] 2023-12-05 10:36
closing

**Closed** 2023-12-05 10:35 UTC
