### ISSUE TITLE
DEV - Minor typo in help text for organization team create

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1569] opened 2024-02-28 07:11 UTC
The current text:
```
shrividyahegde@Hegde ~ % astro organization team create -h
Create an Astro Team

Current Context: Astro

Usage:
  astro organization team create [flags]

Aliases:
  create, cr

Flags:
  -d, --description string   Description of the Team. If the description contains a space, specify the entire team in quotes ""
  -h, --help                 help for create
  -n, --name string          The Team's name. If the name contains a space, specify the entire team within quotes "" 
  -r, --role string          The role for the token. Possible values areORGANIZATION_MEMBER, ORGANIZATION_BILLING_ADMIN, and ORGANIZATION_OWNER

Global Flags:
      --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")
      ```
      
      Expected: Spacing to be fixed at the line "Possible values areORGANIZATION_MEMBER"
      
**What CLI Version did you experience this bug?**
1.24.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by shri-astro** [comment] 2024-03-04 12:10
Issue is unresolved:
```
shrividyahegde@Hegde testlimits % astro organization team create -h
Create an Astro Team

Current Context: Astro

Usage:
  astro organization team create [flags]

Aliases:
  create, cr

Flags:
  -d, --description string   Description of the Team. If the description contains a space, specify the entire team in quotes ""
  -h, --help                 help for create
  -n, --name string          The Team's name. If the name contains a space, specify the entire team within quotes "" 
  -r, --role string          The role for the token. Possible values areORGANIZATION_MEMBER, ORGANIZATION_BILLING_ADMIN, and ORGANIZATION_OWNER

Global Flags:
      --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")

shrividyahegde@Hegde testlimits % astro version
Astro CLI Version: 1.24.1
```

**Comment by kushalmalani** [comment] 2024-03-04 16:23
This change is not released yet, but the issue is fixed on main branch. Should be part of the next release

**Closed by kushalmalani** 2024-03-04 16:23 UTC
Labels: from_qa, minor, team/cp-applications
