### ISSUE TITLE
workspace create command

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#986] opened 2022-12-23 15:22 UTC
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

**Comment by kushalmalani** [comment] 2023-04-11 19:40
Duplicate of https://github.com/astronomer/astro-cli/issues/1131

**Closed by kushalmalani** 2023-04-11 19:40 UTC
Labels: team/ma-practitioner
